//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.07 at 07:17:56 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.web.SOAPAPIS.allapis/deleteEmployee", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package allapis.soapapis.web.com.deleteemployee;
